#!/bin/bash

filename=$1


if [ -e $filename ]; then
	echo "WARNNING: $filename exists."
	exit;
fi

touch $1 

echo "/* $1 */

// written by lina <lina.oahz@gmail.com> 
// start: `date`
//   end:

#include <iostream>
using namespace std;

int main(){

    return 0;
}

" >> $1

gvim $1
