#!/bin/sh

filename=$1


if [ -e $filename ]; then
	echo "WARNNING: $filename exists."
	exit;
fi

touch $1 

echo "/* $1 */

// written by lina <lina.oahz@gmail.com> on `date`
//

#include <stdio.h>

" >> $1

chmod +x $1
gvim $1
